// console.log("Shift and pop");
// var myStack = [];
// myStack.push(1);
// myStack.push(2);
// myStack.push(3);
// console.log(myStack);
// console.log(myStack.pop());
// console.log(myStack);
// console.log("Shift and unshift");
// var myQueue = [];
// myQueue.push("B");
// myQueue.push("C");
// myQueue.push("D");
// console.log(myQueue);
// console.log(myQueue.shift());
// console.log(myQueue.shift());
// console.log(myQueue.shift());
// var myOtherArray = [];
// myOtherArray.push("ipsum");
// myOtherArray.push("dolor");
// myOtherArray.push("sit");
// console.log(myOtherArray);
// myOtherArray.unshift("lorem");
// console.log(myOtherArray);
// console.log("Splicing");
// var myArray = [0,1,2,3,4,5,6,7,8,9];
// console.log(myArray);
// var splice = myArray.splice(3,5);
// console.log(splice);
// console.log(myArray);
var myArray = [true, "What is the meaning of life?"];
myArray.push(42);
myArray.shift();
console.log(myArray[0]);
console.log(myArray[1]);